language: r
sudo: required

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libv8-3.14-dev

matrix:
  include:
    - os: linux
      r: oldrel

    - os: linux
      r: devel

    - os: linux
      r: release

    - os: osx
      r: devel

    - os: osx
      r: release

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::codecov()'
