language: r
sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev
  - sudo apt-get install -y libv8-3.14-dev

r:
  - release
  - oldrel

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::codecov()'
