language: r
sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev
  - sudo apt-get install -y libv8-3.14-dev

r:
  - release
  - devel
  - oldrel

matrix:
  allow_failures:
    - r: devel

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::codecov()'
