language: r
sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev
  - sudo apt-get install -y libv8-3.14-dev


matrix:
  include:
    - os: linux
      r: oldrel

    - os: linux
      r: devel

    - os: linux
      r: release

    - os: osx
      r: devel

    - os: osx
      r: release

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::codecov()'
