language: r
sudo: required

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

matrix:
  include:
    - os: linux
      r: oldrel

    - os: linux
      r: devel

    - os: linux
      r: release
      after_success:
        - Rscript -e 'covr::codecov()'
      before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true

    - os: osx
      r: release

  allow_failures:
    - os: osx

warnings_are_errors: true
