# This script is used to update the string-encoded tree and
# associated/mapped time-zones from https://raw.githubusercontent.com/darkskyapp/tz-lookup/master/tz.js
# that are stored in src/generated-vars.h

library(stringi)

tf <- tempfile(fileext = ".js")
on.exit(unlink(tf), add=TRUE)

# Grab the pre-computed string tree and mapped TZ list
download.file(
  "https://raw.githubusercontent.com/darkskyapp/tz-lookup/master/tz.js",
  tf
)

l <- stri_read_lines(tf)
l <- sub('function tzlookup(Y,W){"use strict";', "", l, fixed=TRUE)
l <- unlist(stri_split_regex(l, '(var T\\=|,U=\\[|;if\\()'))

l[2] <- stri_replace_all_regex(l[2], '^"|"$', "")
l[3] <- stri_replace_last_regex(l[3], "\\]$", "")

# Overwrite src/generated-vars.h
cat(
  "// This file is automatically generated by data-src/generate-vars.R\n",
  "// DO NOT MODIFY BY HAND as all changes will eventually be overwritten\n",
  "// File generate at: ", as.character(Sys.time(), usetz = TRUE), "\n\n",
  sprintf('const char *TZDATA = "%s";\n\n', l[2]),
  "const char *_TZLIST[] = {\n  ",
  l[3],
  "\n};\n\n",
  sep = "", file = here::here("src/generated-vars.h")
)

message(
  "RStudio kinda hates long lines. Do not edit (viewing should be OK) 'src/generated-vars.h' in RStudio.\n\n",
  "REMEMBER TO RE-BUILD AND RE-TEST THE PACKAGE"
)

unlink(tf)
