// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// timezone_lookup_coords_rcpp
Rcpp::CharacterVector timezone_lookup_coords_rcpp(Rcpp::NumericVector latv, Rcpp::NumericVector lonv);
RcppExport SEXP _lutz_timezone_lookup_coords_rcpp(SEXP latvSEXP, SEXP lonvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type latv(latvSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lonv(lonvSEXP);
    rcpp_result_gen = Rcpp::wrap(timezone_lookup_coords_rcpp(latv, lonv));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lutz_timezone_lookup_coords_rcpp", (DL_FUNC) &_lutz_timezone_lookup_coords_rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_lutz(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
