# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timezone_lookup_coords_rcpp <- function(latv, lonv) {
    .Call(`_lutz_timezone_lookup_coords_rcpp`, latv, lonv)
}

