on: [push, pull_request]

name: R-CMD-check-docker

jobs:
  R-CMD-check-docker:
    runs-on: ubuntu-latest
    container: jakubnowosad/geocompr_proj6
    strategy:
      matrix:
        config:
          - {dev_sp_rgdal: true}
          - {dev_sp_rgdal: false}
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: Rscript -e "install.packages('remotes')" -e "remotes::install_deps(dependencies = TRUE)" -e "remotes::install_cran('rcmdcheck')"

      - name: Install dev sp andrgdal
        if: matrix.config.dev_sp_rgdal == true
        run: |
          Rscript -e "remotes::install_github('rsbivand/sp')" -e "install.packages('rgdal', repos='http://R-Forge.R-project.org', type='source')"

      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'warning', check_dir = 'check')"

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-docker-geocompr-results
          path: check
